2021-05-21 04:10:21,000 INFO [n-c5351f81aece.a-c5351e65ee69.ServerMetaBean] - Logging game C:\Users\sinam\IdeaProjects\aot34\logs\game_210521-041021_189065954.txt
2021-05-21 04:10:21,009 ERROR [n-c5351f81aece.a-c5351e65ee69.ServerMetaBean] - Failed to log game results to file
java.nio.file.NoSuchFileException: logs\game_210521-041021_189065954.txt
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
	at java.base/java.nio.file.Files.write(Files.java:3556)
	at java.base/java.nio.file.Files.write(Files.java:3607)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean.logGameResults(ServerBean.java:456)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean.execute(ServerBean.java:376)
	at de.dailab.jiactng.agentcore.execution.BasicExecutionCycle$1.run(BasicExecutionCycle.java:79)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-21 04:10:21,712 WARN [org.apache.activemq.broker.TransportConnection.Transport] - Transport Connection to: tcp://192.168.178.40:61883 failed: java.net.SocketException: Connection reset
2021-05-21 04:10:21,715 WARN [org.apache.activemq.network.DemandForwardingBridgeSupport] - Network connection between vm://n-c5351f81aeceStandardJMSBroker#4 and tcp:///192.168.178.40:61880@61882 shutdown due to a remote error: java.net.SocketException: Connection reset
2021-05-21 04:11:01,672 WARN [n-c5351f81aece.IDirectory] - Forget nodes due to missing alive message:

2021-05-21 04:11:01,673 WARN [n-c5351f81aece.IDirectory] - 	df@n-c535e00afbfe
